"""tablas iniciales

Revision ID: 174c336d0c8f
Revises: 
Create Date: 2026-09-27 15:34:14.226278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174c336d0c8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aduanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aduanas_codigo'), 'aduanas', ['codigo'], unique=True)
    op.create_index(op.f('ix_aduanas_id'), 'aduanas', ['id'], unique=False)
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_almacenes_codigo'), 'almacenes', ['codigo'], unique=True)
    op.create_index(op.f('ix_almacenes_id'), 'almacenes', ['id'], unique=False)
    op.create_table('buques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buques_codigo'), 'buques', ['codigo'], unique=True)
    op.create_index(op.f('ix_buques_id'), 'buques', ['id'], unique=False)
    op.create_table('categorias_trabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_trabajador_id'), 'categorias_trabajador', ['id'], unique=False)
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudades_codigo'), 'ciudades', ['codigo'], unique=True)
    op.create_index(op.f('ix_ciudades_id'), 'ciudades', ['id'], unique=False)
    op.create_table('condiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condiciones_codigo'), 'condiciones', ['codigo'], unique=True)
    op.create_index(op.f('ix_condiciones_id'), 'condiciones', ['id'], unique=False)
    op.create_table('embalajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embalajes_codigo'), 'embalajes', ['codigo'], unique=True)
    op.create_index(op.f('ix_embalajes_id'), 'embalajes', ['id'], unique=False)
    op.create_table('equipamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamientos_codigo'), 'equipamientos', ['codigo'], unique=True)
    op.create_index(op.f('ix_equipamientos_id'), 'equipamientos', ['id'], unique=False)
    op.create_table('incoterms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoterms_codigo'), 'incoterms', ['codigo'], unique=True)
    op.create_index(op.f('ix_incoterms_id'), 'incoterms', ['id'], unique=False)
    op.create_table('lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_codigo'), 'lineas', ['codigo'], unique=True)
    op.create_index(op.f('ix_lineas_id'), 'lineas', ['id'], unique=False)
    op.create_table('monedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monedas_codigo'), 'monedas', ['codigo'], unique=True)
    op.create_index(op.f('ix_monedas_id'), 'monedas', ['id'], unique=False)
    op.create_table('navieras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navieras_codigo'), 'navieras', ['codigo'], unique=True)
    op.create_index(op.f('ix_navieras_id'), 'navieras', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_codigo'), 'pagos', ['codigo'], unique=True)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paises_codigo'), 'paises', ['codigo'], unique=True)
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    op.create_table('peligros_imo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peligros_imo_codigo'), 'peligros_imo', ['codigo'], unique=True)
    op.create_index(op.f('ix_peligros_imo_id'), 'peligros_imo', ['id'], unique=False)
    op.create_table('puertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puertos_codigo'), 'puertos', ['codigo'], unique=True)
    op.create_index(op.f('ix_puertos_id'), 'puertos', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('rubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubros_codigo'), 'rubros', ['codigo'], unique=True)
    op.create_index(op.f('ix_rubros_id'), 'rubros', ['id'], unique=False)
    op.create_table('tipos_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_carga_codigo'), 'tipos_carga', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_carga_id'), 'tipos_carga', ['id'], unique=False)
    op.create_table('tipos_compania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_compania_codigo'), 'tipos_compania', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_compania_id'), 'tipos_compania', ['id'], unique=False)
    op.create_table('tipos_contenedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_contenedor_codigo'), 'tipos_contenedor', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_contenedor_id'), 'tipos_contenedor', ['id'], unique=False)
    op.create_table('tipos_identificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_identificacion_codigo'), 'tipos_identificacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_identificacion_id'), 'tipos_identificacion', ['id'], unique=False)
    op.create_table('tipos_manifiesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_manifiesto_codigo'), 'tipos_manifiesto', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_manifiesto_id'), 'tipos_manifiesto', ['id'], unique=False)
    op.create_table('tipos_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('codigo_aduana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_transporte_codigo'), 'tipos_transporte', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_transporte_id'), 'tipos_transporte', ['id'], unique=False)
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajadores_id'), 'trabajadores', ['id'], unique=False)
    op.create_table('companias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_identificacion_id', sa.Integer(), nullable=True),
    sa.Column('numero_id', sa.String(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['tipo_identificacion_id'], ['tipos_identificacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companias_id'), 'companias', ['id'], unique=False)
    op.create_table('itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buque_id', sa.Integer(), nullable=True),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('viaje', sa.String(), nullable=True),
    sa.Column('puerto_arribo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_llegada', sa.Date(), nullable=True),
    sa.Column('mrn', sa.String(), nullable=True),
    sa.Column('aduana_id', sa.Integer(), nullable=True),
    sa.Column('anio_operacion', sa.Integer(), nullable=True),
    sa.Column('manifiesto', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aduana_id'], ['aduanas.id'], ),
    sa.ForeignKeyConstraint(['buque_id'], ['buques.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas.id'], ),
    sa.ForeignKeyConstraint(['puerto_arribo_id'], ['puertos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerario_id'), 'itinerario', ['id'], unique=False)
    op.create_table('trabajador_categoria',
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_trabajador.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('trabajador_id', 'categoria_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('bl_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerario_id', sa.Integer(), nullable=True),
    sa.Column('codigo_bl_master', sa.String(), nullable=True),
    sa.Column('secuencial', sa.String(), nullable=True),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('naviera_id', sa.Integer(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('puerto_embarque_id', sa.Integer(), nullable=True),
    sa.Column('fecha_embarque', sa.Date(), nullable=True),
    sa.Column('bultos', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('volumen', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['itinerario_id'], ['itinerario.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas.id'], ),
    sa.ForeignKeyConstraint(['naviera_id'], ['navieras.id'], ),
    sa.ForeignKeyConstraint(['puerto_embarque_id'], ['puertos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bl_master_id'), 'bl_master', ['id'], unique=False)
    op.create_table('compania_tipo',
    sa.Column('compania_id', sa.Integer(), nullable=False),
    sa.Column('tipo_compania_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compania_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['tipo_compania_id'], ['tipos_compania.id'], ),
    sa.PrimaryKeyConstraint('compania_id', 'tipo_compania_id')
    )
    op.create_table('routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_routing', sa.String(), nullable=False),
    sa.Column('compania_cliente_id', sa.Integer(), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('incoterm_id', sa.Integer(), nullable=True),
    sa.Column('puerto_origen_id', sa.Integer(), nullable=True),
    sa.Column('consignee_id', sa.Integer(), nullable=True),
    sa.Column('notify_id', sa.Integer(), nullable=True),
    sa.Column('puerto_destino_id', sa.Integer(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.Column('iva_porcentaje', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['compania_cliente_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['consignee_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], ),
    sa.ForeignKeyConstraint(['notify_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['puerto_destino_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['puerto_origen_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_routing')
    )
    op.create_index(op.f('ix_routing_id'), 'routing', ['id'], unique=False)
    op.create_table('bl_hijo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bl_master_id', sa.Integer(), nullable=True),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('itinerario_id', sa.Integer(), nullable=True),
    sa.Column('codigo_bl', sa.String(), nullable=True),
    sa.Column('secuencial', sa.String(), nullable=True),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('naviera_id', sa.Integer(), nullable=True),
    sa.Column('origen_id', sa.Integer(), nullable=True),
    sa.Column('embarcador_id', sa.Integer(), nullable=True),
    sa.Column('consignatario_id', sa.Integer(), nullable=True),
    sa.Column('notificado1_id', sa.Integer(), nullable=True),
    sa.Column('notificado2_id', sa.Integer(), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('puerto_embarque_id', sa.Integer(), nullable=True),
    sa.Column('fecha_embarque', sa.Date(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('puerto_destino_id', sa.Integer(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('coloading', sa.Boolean(), nullable=True),
    sa.Column('bl_guia_primario', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('marcas_numeros', sa.String(), nullable=True),
    sa.Column('descripcion_bienes', sa.String(), nullable=False),
    sa.Column('instrucciones_handling', sa.String(), nullable=True),
    sa.Column('valor_a_declarar', sa.Float(), nullable=True),
    sa.Column('moneda_flete_id', sa.Integer(), nullable=True),
    sa.Column('pago_flete_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['bl_master_id'], ['bl_master.id'], ),
    sa.ForeignKeyConstraint(['consignatario_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['embarcador_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['itinerario_id'], ['itinerario.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas.id'], ),
    sa.ForeignKeyConstraint(['moneda_flete_id'], ['monedas.id'], ),
    sa.ForeignKeyConstraint(['naviera_id'], ['navieras.id'], ),
    sa.ForeignKeyConstraint(['notificado1_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['notificado2_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['origen_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['pago_flete_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['puerto_destino_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['puerto_embarque_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bl_hijo_id'), 'bl_hijo', ['id'], unique=False)
    op.create_table('routing_contenedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('tipo_contenedor_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routing.id'], ),
    sa.ForeignKeyConstraint(['tipo_contenedor_id'], ['tipos_contenedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_contenedores_id'), 'routing_contenedores', ['id'], unique=False)
    op.create_table('routing_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('compra', sa.Float(), nullable=True),
    sa.Column('venta', sa.Float(), nullable=True),
    sa.Column('aplica_iva', sa.Boolean(), nullable=True),
    sa.Column('incluir_en_bl_hijo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routing.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_valores_id'), 'routing_valores', ['id'], unique=False)
    op.create_table('contenedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bl_hijo_id', sa.Integer(), nullable=True),
    sa.Column('numero_contenedor', sa.String(), nullable=True),
    sa.Column('sello1', sa.String(), nullable=True),
    sa.Column('sello2', sa.String(), nullable=True),
    sa.Column('sello3', sa.String(), nullable=True),
    sa.Column('sello4', sa.String(), nullable=True),
    sa.Column('tipo_contenedor_id', sa.Integer(), nullable=True),
    sa.Column('equipamiento_id', sa.Integer(), nullable=True),
    sa.Column('condicion_id', sa.Integer(), nullable=True),
    sa.Column('no_bultos', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('volumen_m3', sa.Float(), nullable=True),
    sa.Column('tipo_carga_id', sa.Integer(), nullable=True),
    sa.Column('embalaje_id', sa.Integer(), nullable=True),
    sa.Column('peligro_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('incluir_en_impresion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bl_hijo_id'], ['bl_hijo.id'], ),
    sa.ForeignKeyConstraint(['condicion_id'], ['condiciones.id'], ),
    sa.ForeignKeyConstraint(['embalaje_id'], ['embalajes.id'], ),
    sa.ForeignKeyConstraint(['equipamiento_id'], ['equipamientos.id'], ),
    sa.ForeignKeyConstraint(['peligro_id'], ['peligros_imo.id'], ),
    sa.ForeignKeyConstraint(['tipo_carga_id'], ['tipos_carga.id'], ),
    sa.ForeignKeyConstraint(['tipo_contenedor_id'], ['tipos_contenedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenedores_id'), 'contenedores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contenedores_id'), table_name='contenedores')
    op.drop_table('contenedores')
    op.drop_index(op.f('ix_routing_valores_id'), table_name='routing_valores')
    op.drop_table('routing_valores')
    op.drop_index(op.f('ix_routing_contenedores_id'), table_name='routing_contenedores')
    op.drop_table('routing_contenedores')
    op.drop_index(op.f('ix_bl_hijo_id'), table_name='bl_hijo')
    op.drop_table('bl_hijo')
    op.drop_index(op.f('ix_routing_id'), table_name='routing')
    op.drop_table('routing')
    op.drop_table('compania_tipo')
    op.drop_index(op.f('ix_bl_master_id'), table_name='bl_master')
    op.drop_table('bl_master')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('trabajador_categoria')
    op.drop_index(op.f('ix_itinerario_id'), table_name='itinerario')
    op.drop_table('itinerario')
    op.drop_index(op.f('ix_companias_id'), table_name='companias')
    op.drop_table('companias')
    op.drop_index(op.f('ix_trabajadores_id'), table_name='trabajadores')
    op.drop_table('trabajadores')
    op.drop_index(op.f('ix_tipos_transporte_id'), table_name='tipos_transporte')
    op.drop_index(op.f('ix_tipos_transporte_codigo'), table_name='tipos_transporte')
    op.drop_table('tipos_transporte')
    op.drop_index(op.f('ix_tipos_manifiesto_id'), table_name='tipos_manifiesto')
    op.drop_index(op.f('ix_tipos_manifiesto_codigo'), table_name='tipos_manifiesto')
    op.drop_table('tipos_manifiesto')
    op.drop_index(op.f('ix_tipos_identificacion_id'), table_name='tipos_identificacion')
    op.drop_index(op.f('ix_tipos_identificacion_codigo'), table_name='tipos_identificacion')
    op.drop_table('tipos_identificacion')
    op.drop_index(op.f('ix_tipos_contenedor_id'), table_name='tipos_contenedor')
    op.drop_index(op.f('ix_tipos_contenedor_codigo'), table_name='tipos_contenedor')
    op.drop_table('tipos_contenedor')
    op.drop_index(op.f('ix_tipos_compania_id'), table_name='tipos_compania')
    op.drop_index(op.f('ix_tipos_compania_codigo'), table_name='tipos_compania')
    op.drop_table('tipos_compania')
    op.drop_index(op.f('ix_tipos_carga_id'), table_name='tipos_carga')
    op.drop_index(op.f('ix_tipos_carga_codigo'), table_name='tipos_carga')
    op.drop_table('tipos_carga')
    op.drop_index(op.f('ix_rubros_id'), table_name='rubros')
    op.drop_index(op.f('ix_rubros_codigo'), table_name='rubros')
    op.drop_table('rubros')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_puertos_id'), table_name='puertos')
    op.drop_index(op.f('ix_puertos_codigo'), table_name='puertos')
    op.drop_table('puertos')
    op.drop_index(op.f('ix_peligros_imo_id'), table_name='peligros_imo')
    op.drop_index(op.f('ix_peligros_imo_codigo'), table_name='peligros_imo')
    op.drop_table('peligros_imo')
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_index(op.f('ix_paises_codigo'), table_name='paises')
    op.drop_table('paises')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_codigo'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_navieras_id'), table_name='navieras')
    op.drop_index(op.f('ix_navieras_codigo'), table_name='navieras')
    op.drop_table('navieras')
    op.drop_index(op.f('ix_monedas_id'), table_name='monedas')
    op.drop_index(op.f('ix_monedas_codigo'), table_name='monedas')
    op.drop_table('monedas')
    op.drop_index(op.f('ix_lineas_id'), table_name='lineas')
    op.drop_index(op.f('ix_lineas_codigo'), table_name='lineas')
    op.drop_table('lineas')
    op.drop_index(op.f('ix_incoterms_id'), table_name='incoterms')
    op.drop_index(op.f('ix_incoterms_codigo'), table_name='incoterms')
    op.drop_table('incoterms')
    op.drop_index(op.f('ix_equipamientos_id'), table_name='equipamientos')
    op.drop_index(op.f('ix_equipamientos_codigo'), table_name='equipamientos')
    op.drop_table('equipamientos')
    op.drop_index(op.f('ix_embalajes_id'), table_name='embalajes')
    op.drop_index(op.f('ix_embalajes_codigo'), table_name='embalajes')
    op.drop_table('embalajes')
    op.drop_index(op.f('ix_condiciones_id'), table_name='condiciones')
    op.drop_index(op.f('ix_condiciones_codigo'), table_name='condiciones')
    op.drop_table('condiciones')
    op.drop_index(op.f('ix_ciudades_id'), table_name='ciudades')
    op.drop_index(op.f('ix_ciudades_codigo'), table_name='ciudades')
    op.drop_table('ciudades')
    op.drop_index(op.f('ix_categorias_trabajador_id'), table_name='categorias_trabajador')
    op.drop_table('categorias_trabajador')
    op.drop_index(op.f('ix_buques_id'), table_name='buques')
    op.drop_index(op.f('ix_buques_codigo'), table_name='buques')
    op.drop_table('buques')
    op.drop_index(op.f('ix_almacenes_id'), table_name='almacenes')
    op.drop_index(op.f('ix_almacenes_codigo'), table_name='almacenes')
    op.drop_table('almacenes')
    op.drop_index(op.f('ix_aduanas_id'), table_name='aduanas')
    op.drop_index(op.f('ix_aduanas_codigo'), table_name='aduanas')
    op.drop_table('aduanas')
    # ### end Alembic commands ###
