"""agregar tabla configuracion

Revision ID: 22955bb7ce86
Revises: 9ffbaa04aa4b
Create Date: 2026-09-30 06:53:36.920739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22955bb7ce86'
down_revision: Union[str, None] = '9ffbaa04aa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_clave'), 'configuracion', ['clave'], unique=True)
    op.create_index(op.f('ix_configuracion_id'), 'configuracion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_id'), table_name='configuracion')
    op.drop_index(op.f('ix_configuracion_clave'), table_name='configuracion')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
