"""tablas iniciales

Revision ID: 9ffbaa04aa4b
Revises: fb4ea4d6e107
Create Date: 2026-09-28 12:21:39.826265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffbaa04aa4b'
down_revision: Union[str, None] = 'fb4ea4d6e107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
