"""agregar cotizacion y ajustar routing

Revision ID: fb4ea4d6e107
Revises: 174c336d0c8f
Create Date: 2026-09-27 16:59:06.538354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4ea4d6e107'
down_revision: Union[str, None] = '174c336d0c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compania_cliente_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.Column('incoterm_id', sa.Integer(), nullable=True),
    sa.Column('shipper_nombre', sa.String(), nullable=True),
    sa.Column('pais_origen_id', sa.Integer(), nullable=True),
    sa.Column('ciudad_origen_id', sa.Integer(), nullable=True),
    sa.Column('puerto_origen_id', sa.Integer(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.Column('usuario_customer_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['ciudad_origen_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['compania_cliente_id'], ['companias.id'], ),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], ),
    sa.ForeignKeyConstraint(['pais_origen_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['puerto_origen_id'], ['puertos.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_customer_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_id'), 'cotizacion', ['id'], unique=False)
    op.create_table('cotizacion_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('compra', sa.Float(), nullable=False),
    sa.Column('venta', sa.Float(), nullable=False),
    sa.Column('aplica_iva', sa.Boolean(), nullable=True),
    sa.Column('incluir_en_bl_hijo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_valores_id'), 'cotizacion_valores', ['id'], unique=False)
    op.add_column('routing', sa.Column('cotizacion_id', sa.Integer(), nullable=True))
    op.add_column('routing', sa.Column('usuario_customer_id', sa.Integer(), nullable=True))
    op.alter_column('routing', 'numero_routing',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'routing', 'usuarios', ['usuario_customer_id'], ['id'])
    op.create_foreign_key(None, 'routing', 'cotizacion', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routing', type_='foreignkey')
    op.drop_constraint(None, 'routing', type_='foreignkey')
    op.alter_column('routing', 'numero_routing',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('routing', 'usuario_customer_id')
    op.drop_column('routing', 'cotizacion_id')
    op.drop_index(op.f('ix_cotizacion_valores_id'), table_name='cotizacion_valores')
    op.drop_table('cotizacion_valores')
    op.drop_index(op.f('ix_cotizacion_id'), table_name='cotizacion')
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
